version: "3.9"

services:
  spoolbud:
    build: .
    container_name: spoolbud
    restart: unless-stopped
    environment:
      SPOOLMAN_BASE: "https://filament.igetno.net"
      SPOOLMAN_API_TOKEN: "${SPOOLMAN_API_TOKEN}"
      COOKIE_NAME: "last_spool_id"
    ports:
      - "8010:8000"
